ALTER TABLE [dbo].[TableTwo]
    ADD CONSTRAINT [PK_TableTwo] PRIMARY KEY CLUSTERED ([Col1] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

