ALTER TABLE [dbo].[TableOne]
    ADD CONSTRAINT [PK_TableOne] PRIMARY KEY CLUSTERED ([Col1] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

