--Alter TableOne to add a new column
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TableOne')
	BEGIN
		IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TableOne' AND COLUMN_NAME='Col4')
			BEGIN			
				ALTER TABLE dbo.TableOne
					ADD [Col4] VARCHAR (50)  NOT NULL;
			END
	END
GO

--Extends TableTwo Col3 datatype from varhcarh to NVARCHAR
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TableTwo')
	BEGIN
		IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='TableTwo' AND COLUMN_NAME='Col3' AND DATA_TYPE='varchar')
			BEGIN
				ALTER TABLE [dbo].[TableTwo]
					ALTER COLUMN [Col3] NVARCHAR (50) NOT NULL
			END
	END
GO