ALTER TABLE [dbo].[TableOne]
    ADD CONSTRAINT [PrimaryKeyStandard]
	PRIMARY KEY NONCLUSTERED ([Col1] ASC)
	WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);